VERSION: "1.1.0" # Internal use only

dimensions:
  # Nether dimension configuration
  nether:
    # Enable or disable teleporting to the Nether dimension (using portal)
    enabled: true
    # Enable or disable the Nether level generation
    # If you have your own Nether world, you can disable this to use it
    generate: true
    # Set the name of the nether level
    name: "nether"
  # End dimension configuration
  end:
    # Enable or disable teleporting to the End dimension (using portal)
    enabled: false
    # Enable or disable the End level generation
    # If you have your own End world, you can disable this to use it
    generate: true
    # Set the name of the end level
    name: "end"
